[package]
name = "tipb_helper"
version = "0.0.1"
edition = "2018"
publish = false

[dependencies]
tipb = { path = "/home/qupeng/github.com/pingcap/tipb" }
codec = { path = "../codec" }
cop_datatype = { path = "../cop_datatype" }
