[package]
name = "test_raftstore"
version = "0.0.1"
publish = false

[dependencies]
tikv = { path = "../../" }
protobuf = "~2.0"
tempdir = "0.3"
raft = "0.4"
futures = "0.1"
tokio-timer = "0.2"
# grpcio = { version = "0.4", features = [ "secure" ] }
rand = "0.3"
log = "0.3.9"
tokio = "0.1.8"

[dependencies.grpcio]
git = "https://github.com/hicqu/grpc-rs.git"
branch = "v0.4-grpc-1.17"
features = ["secure"]

[dependencies.kvproto]
git = "https://github.com/pingcap/kvproto.git"
branch = "super-batch-streaming-grpc-1.17"

[dependencies.rocksdb]
git = "https://github.com/pingcap/rust-rocksdb.git"

